<a href="https://colab.research.google.com/github/bernimof/TD_CsdeDatos/blob/M3_Analisis_de_Caso_Numpy/AnalisisdeCaso1_Libreria_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Aplicación de NumPy en el Análisis de Datos**

## **Desarrollo del Caso**

### **Con Numpy**

1. Carga y estructuación de datos:
- Crea un array NumPy con datos financieros simulados (por ejemplo,
precios de acciones en diferentes días).
- Organiza los datos en una matriz de 5x5, donde cada fila representa
una acción y cada columna un día de cotización.

En una matriz bidimensional de los precios de acciones, tenemos dos ejes, donde:

-	Cada fila representa una acción.
-	Cada columna representa un día de cotización.

In [ ]:
import numpy as np

matriz = np.random.randint(1, 100, size=(5, 5))
print(matriz)

[[ 5 38 27 85 24]
 [19 54 35 16 13]
 [96 46 78  2 23]
 [70 48 73 88 19]
 [31 53 17 22 20]]


2. Análisis y transformación de datos:

- Obtén el promedio, valor máximo y mínimo de cada acción a lo
largo del tiempo.

In [ ]:
print("Promedio de cada acción: \n", np.mean(matriz, axis=1),"\n")
print("Máximo de cada acción: \n", np.max(matriz, axis=1),"\n")
print("Mínimo de cada acción: \n", np.min(matriz, axis=1))

Promedio de cada acción: 
 [35.8 27.4 49.  59.6 28.6] 

Máximo de cada acción: 
 [85 54 96 88 53] 

Mínimo de cada acción: 
 [ 5 13  2 19 17]


- Calcula la variación porcentual diaria de cada acción.

In [ ]:
variacion_porcentual = np.diff(matriz, axis=1) / matriz[:, :-1] * 100
print("Variación porcentual diaria de cada acción: \n", variacion_porcentual, "\n")

Variación porcentual diaria de cada acción: 
 [[ 660.          -28.94736842  214.81481481  -71.76470588]
 [ 184.21052632  -35.18518519  -54.28571429  -18.75      ]
 [ -52.08333333   69.56521739  -97.43589744 1050.        ]
 [ -31.42857143   52.08333333   20.54794521  -78.40909091]
 [  70.96774194  -67.9245283    29.41176471   -9.09090909]] 



- Aplica funciones matemáticas como logaritmo, exponencial o
normalización sobre los datos.

In [ ]:
log = np.log(matriz)
exp = np.exp(matriz)

print("Logaritmo natural de cada acción: \n",log, "\n")
print("Exponencial de cada acción: \n",exp)

Logaritmo natural de cada acción: 
 [[1.60943791 3.63758616 3.29583687 4.44265126 3.17805383]
 [2.94443898 3.98898405 3.55534806 2.77258872 2.56494936]
 [4.56434819 3.8286414  4.35670883 0.69314718 3.13549422]
 [4.24849524 3.87120101 4.29045944 4.47733681 2.94443898]
 [3.4339872  3.97029191 2.83321334 3.09104245 2.99573227]] 

Exponencial de cada acción: 
 [[1.48413159e+02 3.18559318e+16 5.32048241e+11 8.22301271e+36
  2.64891221e+10]
 [1.78482301e+08 2.83075330e+23 1.58601345e+15 8.88611052e+06
  4.42413392e+05]
 [4.92345829e+41 9.49611942e+19 7.49841700e+33 7.38905610e+00
  9.74480345e+09]
 [2.51543867e+30 7.01673591e+20 5.05239363e+31 1.65163625e+38
  1.78482301e+08]
 [2.90488497e+13 1.04137594e+23 2.41549528e+07 3.58491285e+09
  4.85165195e+08]]


In [ ]:
# Normalización de los datos: (valor - mínimo) / (máximo - mínimo)
normalizacion = (matriz - np.min(matriz, axis=1, keepdims=True)) / (np.max(matriz, axis=1, keepdims=True) - np.min(matriz, axis=1, keepdims=True))
print("\nPrecios de las acciones normalizados:")
print(normalizacion)


Precios de las acciones normalizados:
[[0.         0.4125     0.275      1.         0.2375    ]
 [0.14634146 1.         0.53658537 0.07317073 0.        ]
 [1.         0.46808511 0.80851064 0.         0.22340426]
 [0.73913043 0.42028986 0.7826087  1.         0.        ]
 [0.38888889 1.         0.         0.13888889 0.08333333]]


3. Optimización y selección de datos:

- Utiliza indexación avanzada para extraer información específica,
como el rendimiento de una acción en un día determinado.

In [ ]:
# Extrae el rendimiento de la primera acción en el segundo día
rendimiento_dia2 = matriz[0, 1]
print("Rendimiento de la primera acción en el segundo día:", rendimiento_dia2)

Rendimiento de la primera acción en el segundo día: 38


- Aplica broadcasting para realizar operaciones sin necesidad de
bucles.

In [ ]:
# Multiplicamos toda la matriz por 2 usando broadcasting
matriz_multiplicada = matriz * 2
print("Matriz multiplicada por 2: \n", matriz_multiplicada, "\n")

Matriz multiplicada por 2: 
 [[ 10  76  54 170  48]
 [ 38 108  70  32  26]
 [192  92 156   4  46]
 [140  96 146 176  38]
 [ 62 106  34  44  40]] 



### **Sin Numpy**

4. Comparación con otros métodos:


- Analiza cómo se podrían realizar estas tareas sin NumPy y compara
la eficiencia en términos de código y rendimiento computacional.

a) Carga y estructuación de datos:

In [ ]:
import random

# Crear una matriz 5x5 con valores aleatorios entre 1 y 100
matriz2 = [[random.randint(1, 100) for _ in range(5)] for _ in range(5)]
print("Matriz de precios de acciones:\n", matriz2)

Matriz de precios de acciones:
 [[11, 6, 28, 43, 10], [57, 52, 74, 77, 75], [43, 65, 1, 66, 71], [9, 32, 7, 51, 42], [83, 9, 47, 12, 85]]


b) Análisis y transformación de datos:

In [ ]:
# Promedio de cada acción
promedio_acciones = [sum(fila) / len(fila) for fila in matriz2]
print("Promedio de cada acción: \n", promedio_acciones, "\n")

# Máximo de cada acción
maximo_acciones = [max(fila) for fila in matriz2]
print("Máximo de cada acción: \n", maximo_acciones, "\n")

# Mínimo de cada acción
minimo_acciones = [min(fila) for fila in matriz2]
print("Mínimo de cada acción: \n", minimo_acciones)

Promedio de cada acción: 
 [19.6, 67.0, 49.2, 28.2, 47.2] 

Máximo de cada acción: 
 [43, 77, 71, 51, 85] 

Mínimo de cada acción: 
 [6, 52, 1, 7, 9]


In [ ]:
# Variación porcentual diaria de cada acción
variacion_porcentual = [
    [(fila[i] - fila[i - 1]) / fila[i - 1] * 100 for i in range(1, len(fila))]
    for fila in matriz2
]
print("Variación porcentual diaria de cada acción: \n", variacion_porcentual)

Variación porcentual diaria de cada acción: 
 [[-45.45454545454545, 366.66666666666663, 53.57142857142857, -76.74418604651163], [-8.771929824561402, 42.30769230769231, 4.054054054054054, -2.5974025974025974], [51.162790697674424, -98.46153846153847, 6500.0, 7.575757575757576], [255.55555555555554, -78.125, 628.5714285714286, -17.647058823529413], [-89.1566265060241, 422.22222222222223, -74.46808510638297, 608.3333333333333]]


In [ ]:
import math

# Aplicar logaritmo natural a cada valor
logaritmo = [[math.log(valor) for valor in fila] for fila in matriz2]
print("Logaritmo natural de cada acción: \n", logaritmo,"\n")

# Aplicar la función exponencial a cada valor
exponencial = [[math.exp(valor) for valor in fila] for fila in matriz2]
print("Exponencial de cada acción: \n", exponencial,"\n")

# Normalización de los valores entre 0 y 1
minimos = [min(fila) for fila in matriz2]
maximos = [max(fila) for fila in matriz2]
normalizado = [
    [(valor - min_val) / (max_val - min_val) for valor, min_val, max_val in zip(fila, minimos, maximos)]
    for fila in matriz2
]
print("Acciones normalizadas: \n", normalizado)

Logaritmo natural de cada acción: 
 [[2.3978952727983707, 1.791759469228055, 3.332204510175204, 3.7612001156935624, 2.302585092994046], [4.04305126783455, 3.9512437185814275, 4.30406509320417, 4.343805421853684, 4.31748811353631], [3.7612001156935624, 4.174387269895637, 0.0, 4.189654742026425, 4.2626798770413155], [2.1972245773362196, 3.4657359027997265, 1.9459101490553132, 3.9318256327243257, 3.7376696182833684], [4.418840607796598, 2.1972245773362196, 3.8501476017100584, 2.4849066497880004, 4.442651256490317]] 

Exponencial de cada acción: 
 [[59874.14171519782, 403.4287934927351, 1446257064291.475, 4.727839468229346e+18, 22026.465794806718], [5.685719999335932e+24, 3.831008000716577e+22, 1.3733829795401761e+32, 2.7585134545231703e+33, 3.7332419967990015e+32], [4.727839468229346e+18, 1.6948892444103338e+28, 2.718281828459045, 4.607186634331292e+28, 6.837671229762744e+30], [8103.083927575384, 78962960182680.69, 1096.6331584284585, 1.4093490824269389e+22, 1.739274941520501e+18], [1.112

c) Optimización y Selección de Datos:

In [ ]:
# Indexación avanzada para extraer información específica
rendimiento_dia2 = matriz2[0][1]
print("Rendimiento de la primera acción en el segundo día:", rendimiento_dia2)

Rendimiento de la primera acción en el segundo día: 6


In [ ]:
# Multiplicar toda la matriz por 2
matriz_multiplicada = [[valor * 2 for valor in fila] for fila in matriz2]
print("Matriz multiplicada por 2: \n", matriz_multiplicada)

Matriz multiplicada por 2: 
 [[22, 12, 56, 86, 20], [114, 104, 148, 154, 150], [86, 130, 2, 132, 142], [18, 64, 14, 102, 84], [166, 18, 94, 24, 170]]


## **Conclusión**

Se pueden realizar con y sin Numpy los mismos cálculos en Python. La gran diferencia es que se genera una mayor cantidad de código sin Numpy. Ya que se deben utilizar varios bucles, lo cual tambien puede generar una mayor posibilidad de error al escribir el código.